# MySQL Database Connection Settings
db.url=jdbc:mysql://localhost:3306/aicamera
db.user=root
db.password=3zP0jFO-ujLjczM8

# 파일 저장 경로 설정 (백슬래시는 2번 쓰거나 슬래시로 변경)
path.temp_videos=C:\\Users\\User\\aicamera_uploads\\temp_videos
path.final_videos=C:\\Users\\User\\aicamera_uploads\\final_videos
